@startuml

title __GRAPH's Class Diagram__\n

  namespace com.example.telecom.paris.maze.graph {
    class com.example.telecom.paris.maze.graph.Dijkstra {
        {static} + findShortestPaths()
        {static} + main()
    }
  }
  

  namespace com.example.telecom.paris.maze.graph {
    interface com.example.telecom.paris.maze.graph.Distance {
        {abstract} + getDistance()
    }
  }
  

  namespace com.example.telecom.paris.maze.graph {
    interface com.example.telecom.paris.maze.graph.Graph {
        {abstract} + getSuccessors()
        {abstract} + getVertex()
        {abstract} + getVertexes()
    }
  }
  

  namespace com.example.telecom.paris.maze.graph {
    interface com.example.telecom.paris.maze.graph.MinDistance {
        {abstract} + getMinDistance()
        {abstract} + getMinDistanceVertex()
        {abstract} + setMinDistance()
    }
  }
  

  namespace com.example.telecom.paris.maze.graph {
    class com.example.telecom.paris.maze.graph.NotAdjacentVerticesException {
    }
  }
  

  namespace com.example.telecom.paris.maze.graph {
    interface com.example.telecom.paris.maze.graph.ProcessedVertexesSet {
        {abstract} + add()
        {abstract} + contains()
    }
  }
  

  namespace com.example.telecom.paris.maze.graph {
    interface com.example.telecom.paris.maze.graph.ShortestPaths {
        {abstract} + getShortestPath()
        {abstract} + setPrevious()
    }
  }
  

  namespace com.example.telecom.paris.maze.graph {
    interface com.example.telecom.paris.maze.graph.Vertex {
        {abstract} + getLabel()
        {abstract} + getSuccessors()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
