@startuml

title __MODEL's Class Diagram__\n

  namespace com.example.telecom.paris.maze.model {
    interface com.example.telecom.paris.maze.model.MazeBoxModel {
        {abstract} + belongsToShortestPath()
        {abstract} + isArrival()
        {abstract} + isDeparture()
        {abstract} + isEmpty()
        {abstract} + isWall()
        {abstract} + setArrival()
        {abstract} + setDeparture()
        {abstract} + setEmpty()
        {abstract} + setWall()
    }
  }
  

  namespace com.example.telecom.paris.maze.model {
    interface com.example.telecom.paris.maze.model.MazeFactory {
        {abstract} + createMazeModel()
    }
  }
  

  namespace com.example.telecom.paris.maze.model {
    interface com.example.telecom.paris.maze.model.MazeModel {
        {abstract} + addObserver()
        {abstract} + clearMaze()
        {abstract} + clearShortestPath()
        {abstract} + getHeigth()
        {abstract} + getId()
        {abstract} + getMazeBox()
        {abstract} + getMazeFactory()
        {abstract} + getNumberOfBoxes()
        {abstract} + getWidth()
        {abstract} + initFromTextFile()
        {abstract} + removeObserver()
        {abstract} + saveToTextFile()
        {abstract} + setId()
        {abstract} + solve()
        {abstract} + validate()
    }
  }
  

  namespace com.example.telecom.paris.maze.model {
    interface com.example.telecom.paris.maze.model.MazePersistenceManager {
        {abstract} + delete()
        {abstract} + persist()
        {abstract} + read()
    }
  }
  

  namespace com.example.telecom.paris.maze.model {
    interface com.example.telecom.paris.maze.model.ModelObserver {
        {abstract} + modelStateChanged()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
